const $=s=>document.querySelector(s); const $$=s=>Array.from(document.querySelectorAll(s));
const days=['Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo']; let currentMonth=new Date(); let plannerMode='cards';
function age(date){if(!date)return'';const b=new Date(date+'T00:00'),n=new Date();let a=n.getFullYear()-b.getFullYear();if(n<new Date(n.getFullYear(),b.getMonth(),b.getDate()))a--;return a}
function fmtDate(d){return d?new Date(d+'T00:00').toLocaleDateString('pt-BR'):''} function ymd(d){return d.toISOString().slice(0,10)}
function nowMinutes(){const n=new Date();return n.getHours()*60+n.getMinutes()} function timeMin(t){if(!t)return 0; const [h,m]=t.split(':').map(Number); return h*60+m}
function eventUrgency(e){const today=new Date(ymd(new Date())+'T00:00'), d=new Date(e.date+'T00:00'); return Math.round((d-today)/86400000)}
function isUpcomingEvent(e){const diff=eventUrgency(e);return diff>=0&&diff<=3}
function show(view){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+view).classList.add('active');$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));render(view)}
function modal(html){$('#modal-content').innerHTML=html;$('#modal').showModal()} function closeModal(){$('#modal').close()}
async function patientOptions(selected=''){const ps=(await all('patients')).sort((a,b)=>a.name.localeCompare(b.name));return '<option value="">Sem paciente específico</option>'+ps.map(p=>`<option value="${p.id}" ${String(selected)===String(p.id)?'selected':''}>${p.name}</option>`).join('')}
async function render(view){if(view==='dashboard')return dashboard(); if(view==='patients')return patients(); if(view==='planner')return planner(); if(view==='calendar')return calendar(); if(view==='backup')return backup();}
function eventLine(e){const diff=eventUrgency(e); const tag=diff===0?'Hoje':diff===1?'Amanhã':diff===3?'Em 3 dias':`Em ${diff} dias`;return `<div class="item event-row"><div><b>${fmtDate(e.date)}</b><br><small>${e.time||''}</small></div><div>${e.title}<br><small>${e.patientName||'Evento geral'} ${e.note?'• '+e.note:''}</small></div><span class="status warn">${tag}</span></div>`}
async function dashboard(){const ev=await all('events'), sch=await all('schedule'); const today=ymd(new Date()); const next=new Date(); next.setDate(next.getDate()+7); const upcoming=ev.filter(e=>e.date>=today&&e.date<=ymd(next)).sort((a,b)=>(a.date+(a.time||'')).localeCompare(b.date+(b.time||''))); const todayEvents=ev.filter(e=>e.date===today).sort((a,b)=>(a.time||'').localeCompare(b.time||'')); const weekday=(new Date().getDay()+6)%7; const todaySch=sch.filter(s=>Number(s.weekday)===weekday).sort((a,b)=>a.time.localeCompare(b.time)); $('#dashboard').innerHTML=`<div class="grid single"><div class="card"><h2>Eventos de hoje</h2>${todayEvents.length?todayEvents.map(e=>`<div class="item"><b>${e.time||''} ${e.title}</b><br><span class="muted">${e.patientName||'Evento geral'} ${e.note?'• '+e.note:''}</span></div>`).join(''):'<div class="empty subtle">Sem eventos extra agendados para hoje.</div>'}</div><div class="card"><h2>Hoje no planner</h2>${todaySch.length?todaySch.map(s=>`<div class="item"><b>${s.time}</b> ${s.patientName||''}<br><span class="muted">${s.note||''}</span></div>`).join(''):'<div class="empty">Nenhum atendimento fixo hoje.</div>'}</div><div class="card"><h2>Próximos 7 dias</h2>${upcoming.length?upcoming.map(eventLine).join(''):'<div class="empty">Nenhum evento próximo.</div>'}</div></div>`; notifyDue(todayEvents, upcoming)}
async function patients(){const ps=(await all('patients')).sort((a,b)=>a.name.localeCompare(b.name)), ev=await all('events'), sch=await all('schedule'); const today=ymd(new Date()), weekday=(new Date().getDay()+6)%7, nmin=nowMinutes(); $('#patients').innerHTML=`<div class="row space"><h1>Pacientes</h1><button class="btn" onclick="patientForm()">+ Novo paciente</button></div><div class="patient-grid">${ps.length?ps.map(p=>{const todaySession=sch.filter(s=>Number(s.patientId)===Number(p.id)&&Number(s.weekday)===weekday).sort((a,b)=>a.time.localeCompare(b.time))[0]; const near=todaySession?timeMin(todaySession.time)-nmin:null; const nextEv=ev.filter(e=>Number(e.patientId)===Number(p.id)&&isUpcomingEvent(e)).sort((a,b)=>(a.date+(a.time||'')).localeCompare(b.date+(b.time||'')))[0]; let badge=''; if(todaySession){badge=near>=0&&near<=60?`<span class="status soon">Sessão em breve • ${todaySession.time}</span>`:`<span class="status ok">Sessão hoje • ${todaySession.time}</span>`} if(nextEv) badge+=` <span class="status warn">🔔 ${eventUrgency(nextEv)===0?'Evento hoje':'Evento próximo'}</span>`; return `<div class="patient-card" onclick="patientDetail(${p.id})"><div><b>${p.name}</b><br><span class="muted">${p.birth?age(p.birth)+' anos':'Idade não informada'}</span></div><div>${badge||'<span class="status neutral">Sem sessão hoje</span>'}</div></div>`}).join(''):'<div class="empty">Nenhum paciente cadastrado ainda.</div>'}</div>`}
function patientForm(p={}){modal(`<form onsubmit="savePatient(event,${p.id||'null'})"><h2>${p.id?'Editar':'Novo'} paciente</h2><div class="form-grid"><label>Nome da criança<input name="name" required value="${p.name||''}"></label><label>Nascimento<input type="date" name="birth" value="${p.birth||''}"></label><label>Nome da mãe<input name="mother" value="${p.mother||''}"></label><label>Telefone da mãe<input name="motherPhone" value="${p.motherPhone||''}"></label><label>Nome do pai<input name="father" value="${p.father||''}"></label><label>Telefone do pai<input name="fatherPhone" value="${p.fatherPhone||''}"></label><label>Status<select name="status"><option ${p.status!=='Inativo'?'selected':''}>Ativo</option><option ${p.status==='Inativo'?'selected':''}>Inativo</option></select></label></div><label>Observações<textarea name="notes">${p.notes||''}</textarea></label><div class="row"><button class="btn">Salvar</button><button type="button" class="btn secondary" onclick="closeModal()">Cancelar</button></div></form>`)}
async function savePatient(e,id){e.preventDefault();const data=Object.fromEntries(new FormData(e.target)); if(id)data.id=Number(id); await save('patients',data); closeModal(); show('patients')}
function patientInfo(p){return `<details class="patient-info"><summary><div><h1>${p.name}</h1><span class="muted">${p.birth?age(p.birth)+' anos':''}</span></div><button class="icon-btn" onclick='event.stopPropagation();patientForm(${JSON.stringify(p)})'>✎</button></summary><p><b>Nascimento:</b> ${fmtDate(p.birth)||'-'}<br><b>Mãe:</b> ${p.mother||'-'} ${p.motherPhone||''}<br><b>Pai:</b> ${p.father||'-'} ${p.fatherPhone||''}</p>${p.notes?`<p>${p.notes}</p>`:''}</details>`}
async function patientDetail(id){const p=await get('patients',id), notes=(await all('notes')).filter(n=>Number(n.patientId)===Number(id)).sort((a,b)=>(b.date+(b.time||'')).localeCompare(a.date+(a.time||''))), evs=(await all('events')).filter(e=>Number(e.patientId)===Number(id)).sort((a,b)=>(a.date+(a.time||'')).localeCompare(b.date+(b.time||''))), sch=(await all('schedule')).filter(s=>Number(s.patientId)===Number(id)).sort((a,b)=>Number(a.weekday)-Number(b.weekday)||a.time.localeCompare(b.time)); show('patient-detail'); $('#patient-detail').innerHTML=`<button class="btn secondary" onclick="show('patients')">← Voltar</button><div class="card">${patientInfo(p)}</div><div class="card"><div class="row space"><h2>Atendimento fixo</h2><button class="btn secondary" onclick="scheduleForm(${p.id})">+ Atendimento</button></div>${sch.length?`<div class="patient-schedule-strip">${sch.map(s=>`<div class="mini-schedule"><b>${days[s.weekday]}</b><span>${s.time}</span><small>${s.note||''}</small><div class="mini-actions"><button class="icon-btn" onclick="scheduleForm(${p.id},${s.id})">✎</button><button class="icon-btn" onclick="deleteSchedule(${s.id},${p.id})">×</button></div></div>`).join('')}</div>`:'<div class="empty">Nenhum atendimento fixo cadastrado.</div>'}</div><div class="grid cards"><div class="card"><div class="row space"><h2>Prontuário</h2><button class="btn" onclick="noteForm(${p.id})">+ Folha</button></div>${notes.length?notes.map(n=>`<div class="note-card" onclick="noteView(${n.id},${p.id})"><b>${fmtDate(n.date)} ${n.time||''}</b><br><span>${n.type||'Registro'}</span></div>`).join(''):'<div class="empty">Nenhuma folha de prontuário.</div>'}</div><div class="card"><div class="row space"><h2>Datas agendadas</h2><button class="btn" onclick="eventForm(${p.id})">+ Data</button></div>${evs.length?evs.map(e=>`<div class="item event-row ${isUpcomingEvent(e)?'highlight':''}"><div><b>${fmtDate(e.date)}</b><br><small>${e.time||''}</small></div><div>${isUpcomingEvent(e)?'🔔 ':''}${e.title}<br><small>${e.note||''}</small></div><div class="mini-actions"><button class="icon-btn" onclick="eventForm(${p.id},${e.id})">✎</button><button class="icon-btn" onclick="deleteEvent(${e.id},${p.id})">×</button></div></div>`).join(''):'<div class="empty">Nenhuma data específica.</div>'}</div></div>`}
async function noteView(id,patientId){const n=await get('notes',id); modal(`<div><h2>${fmtDate(n.date)} ${n.time||''} — ${n.type||'Registro'}</h2><p style="white-space:pre-wrap">${n.text||''}</p><div class="row"><button class="btn secondary" onclick="noteForm(${patientId},${id})">Editar</button><button class="btn danger" onclick="deleteNote(${id},${patientId})">Remover</button><button class="btn" onclick="closeModal()">Fechar</button></div></div>`)}
async function noteForm(patientId,id=''){let n={date:ymd(new Date()),time:new Date().toTimeString().slice(0,5)}; if(id)n=await get('notes',id)||n; modal(`<form onsubmit="saveNote(event,${patientId},${id||'null'})"><h2>${id?'Editar':'Nova'} folha do prontuário</h2><div class="form-grid"><label>Data<input type="date" name="date" value="${n.date}" required></label><label>Hora<input type="time" name="time" value="${n.time||''}"></label><label>Tipo<select name="type">${['Sessão','Orientação aos pais','Avaliação','Reunião escolar','Supervisão','Intercorrência'].map(t=>`<option ${n.type===t?'selected':''}>${t}</option>`).join('')}</select></label></div><label>Registro<textarea name="text" required>${n.text||''}</textarea></label><div class="row"><button class="btn">Salvar</button><button type="button" class="btn secondary" onclick="closeModal()">Cancelar</button></div></form>`)}
async function saveNote(e,patientId,id){e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.patientId=Number(patientId); if(id)data.id=Number(id); await save('notes',data); closeModal(); patientDetail(patientId)}
async function deleteNote(id,patientId){if(confirm('Remover esta folha?')){await del('notes',id);closeModal();patientDetail(patientId)}}
async function planner(){const sch=(await all('schedule')).sort((a,b)=>Number(a.weekday)-Number(b.weekday)||a.time.localeCompare(b.time)); const shownDays=[0,1,2,3,4].concat(sch.some(s=>Number(s.weekday)===5)?[5]:[], sch.some(s=>Number(s.weekday)===6)?[6]:[]); $('#planner').innerHTML=`<div class="row space"><div><h1>Planner semanal</h1><p class="muted">Cadastre os atendimentos fixos conforme forem surgindo.</p></div><div class="row"><button class="btn secondary" onclick="plannerMode=plannerMode==='cards'?'week':'cards';planner()">${plannerMode==='cards'?'Ver semana horizontal':'Ver cards'}</button><button class="btn secondary" onclick="exportPlannerImage()">Exportar imagem</button><button class="btn" onclick="scheduleForm()">+ Atendimento fixo</button></div></div>${plannerMode==='week'?weekPlanner(sch,shownDays):cardPlanner(sch,shownDays)}`}
function cardPlanner(sch,shownDays){return `<div class="planner-days">${shownDays.map(i=>{const items=sch.filter(s=>Number(s.weekday)===i);return `<div class="day-card"><h3>${days[i]}</h3>${items.length?items.map(scheduleItem).join(''):'<div class="empty">Sem atendimento cadastrado.</div>'}</div>`}).join('')}</div>`}
function scheduleItem(s){return `<div class="schedule-item"><div><b>${s.time}</b> ${s.patientName||''}<br><span class="muted">${s.note||''}</span></div><div class="mini-actions"><button class="icon-btn" onclick="scheduleForm('',${s.id})">✎</button><button class="icon-btn" onclick="deleteSchedule(${s.id})">×</button></div></div>`}
function weekPlanner(sch,shownDays){return `<div id="planner-export" class="week-planner">${shownDays.map(i=>`<div class="week-col"><h3>${days[i]}</h3>${sch.filter(s=>Number(s.weekday)===i).map(s=>`<div class="week-item"><b>${s.time}</b><br>${s.patientName||''}<small>${s.note||''}</small></div>`).join('')||'<div class="empty small">Livre</div>'}</div>`).join('')}</div>`}
async function scheduleForm(patientId='',id=''){let item={patientId}; if(id)item=await get('schedule',id)||{}; modal(`<form onsubmit="saveSchedule(event,${id||'null'},'${patientId||''}')"><h2>${id?'Editar':'Novo'} atendimento fixo</h2><div class="form-grid"><label>Dia<select name="weekday">${days.map((d,i)=>`<option value="${i}" ${String(item.weekday)===String(i)?'selected':''}>${d}</option>`).join('')}</select></label><label>Horário<input type="time" name="time" required value="${item.time||''}"></label><label>Paciente<select name="patientId" required>${await patientOptions(item.patientId||patientId)}</select></label></div><label>Observação<input name="note" value="${item.note||''}"></label><div class="row"><button class="btn">Salvar</button><button type="button" class="btn secondary" onclick="closeModal()">Cancelar</button></div></form>`)}
async function saveSchedule(e,id,returnPatientId=''){e.preventDefault();const data=Object.fromEntries(new FormData(e.target)); if(id)data.id=Number(id); const p=await get('patients',data.patientId); data.patientName=p?.name||''; data.patientId=Number(data.patientId); await save('schedule',data); closeModal(); returnPatientId?patientDetail(returnPatientId):planner()}
async function deleteSchedule(id,returnPatientId=''){if(confirm('Remover este atendimento fixo?')){await del('schedule',id); returnPatientId?patientDetail(returnPatientId):planner()}}
async function eventForm(patientId='',id=''){let item={patientId,date:ymd(new Date())}; if(id)item=await get('events',id)||item; modal(`<form onsubmit="saveEvent(event,${id||'null'},'${patientId||''}')"><h2>${id?'Editar':'Nova'} data / evento</h2><div class="form-grid"><label>Título<input name="title" required value="${item.title||''}"></label><label>Data<input type="date" name="date" required value="${item.date||ymd(new Date())}"></label><label>Horário<input type="time" name="time" value="${item.time||''}"></label><label>Paciente vinculado<select name="patientId">${await patientOptions(item.patientId||patientId)}</select></label></div><label>Observação<textarea name="note">${item.note||''}</textarea></label><div class="row"><button class="btn">Salvar</button><button type="button" class="btn secondary" onclick="closeModal()">Cancelar</button></div></form>`)}
async function saveEvent(e,id,returnPatientId=''){e.preventDefault();const data=Object.fromEntries(new FormData(e.target)); if(id)data.id=Number(id); if(data.patientId){const p=await get('patients',data.patientId); data.patientName=p?.name||''; data.patientId=Number(data.patientId)}else{data.patientId='';data.patientName=''} await save('events',data); closeModal(); returnPatientId?patientDetail(returnPatientId):calendar()}
async function calendar(){const ev=(await all('events')).sort((a,b)=>(a.date+(a.time||'')).localeCompare(b.date+(b.time||''))); const y=currentMonth.getFullYear(),m=currentMonth.getMonth(); const first=new Date(y,m,1), start=new Date(first); start.setDate(first.getDate()-((first.getDay()+6)%7)); const cells=[]; for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);cells.push(d)} const monthName=currentMonth.toLocaleDateString('pt-BR',{month:'long',year:'numeric'}); const monthEvents=ev.filter(e=>{const d=new Date(e.date+'T00:00');return d.getMonth()===m&&d.getFullYear()===y}); $('#calendar').innerHTML=`<div class="calendar-head"><button class="btn secondary" onclick="currentMonth.setMonth(currentMonth.getMonth()-1);calendar()">←</button><div><h1>Agenda</h1><p class="muted">${monthName}</p></div><div class="row"><button class="btn" onclick="eventForm()">+ Evento</button><button class="btn secondary" onclick="currentMonth=new Date();calendar()">Hoje</button><button class="btn secondary" onclick="currentMonth.setMonth(currentMonth.getMonth()+1);calendar()">→</button></div></div><div class="calendar-grid">${days.map(d=>`<div class="day-name">${d.slice(0,3)}</div>`).join('')}${cells.map(d=>{const key=ymd(d), list=ev.filter(e=>e.date===key).sort((a,b)=>(a.time||'').localeCompare(b.time||''));return `<div class="day ${d.getMonth()!==m?'out':''} ${key===ymd(new Date())?'today':''}"><div class="day-num">${d.getDate()}</div>${list.map(e=>`<span class="event" title="${e.title}">${e.time||''} ${e.title}</span>`).join('')}</div>`}).join('')}</div><div class="card event-list"><div class="row space"><h2>Eventos cadastrados no mês</h2><button class="btn secondary" onclick="eventForm()">+ Cadastrar</button></div>${monthEvents.length?monthEvents.map(e=>`<div class="item event-row"><div><b>${fmtDate(e.date)}</b><br><small>${e.time||''}</small></div><div>${e.title}<br><small>${e.patientName||'Evento geral'} ${e.note?'• '+e.note:''}</small></div><div class="mini-actions"><button class="icon-btn" onclick="eventForm('',${e.id})">✎</button><button class="icon-btn" onclick="deleteEvent(${e.id})">×</button></div></div>`).join(''):'<div class="empty">Nenhum evento neste mês.</div>'}</div>`}
async function deleteEvent(id,returnPatientId=''){if(confirm('Remover este evento da agenda?')){await del('events',id); returnPatientId?patientDetail(returnPatientId):calendar()}}
async function backup(){ $('#backup').innerHTML=`<h1>Backup</h1><div class="grid cards"><div class="card"><h2>Notificações</h2><p class="muted">O app avisa dentro do sistema e tenta usar notificações do navegador quando houver evento hoje, amanhã ou em 3 dias. No Android, a notificação depende do Chrome/PWA permitir.</p><button class="btn" onclick="askNotification()">Permitir notificações</button></div><div class="card"><h2>Exportar dados</h2><p class="muted">Gera um arquivo JSON com pacientes, prontuários, agenda e eventos. Depois dá para salvar no Google Drive manualmente.</p><button class="btn" onclick="downloadBackup()">Baixar backup</button></div><div class="card"><h2>Importar backup</h2><p class="muted">Use para restaurar dados neste dispositivo.</p><input type="file" accept="application/json" onchange="uploadBackup(event)"></div></div>`}
async function askNotification(){if(!('Notification' in window))return alert('Este navegador não suporta notificações.'); const p=await Notification.requestPermission(); alert(p==='granted'?'Notificações permitidas.':'Notificações não foram permitidas.')}
function notifyDue(todayEvents, upcoming){if(!('Notification' in window)||Notification.permission!=='granted')return; const key='abaNotif-'+ymd(new Date()); if(localStorage.getItem(key))return; const due=upcoming.filter(e=>[0,1,3].includes(eventUrgency(e))); if(due.length){new Notification('Agenda ABA', {body:`Você tem ${due.length} evento(s) próximo(s): hoje, amanhã ou em 3 dias.`}); localStorage.setItem(key,'1')}}
async function exportPlannerImage(){const sch=(await all('schedule')).sort((a,b)=>Number(a.weekday)-Number(b.weekday)||a.time.localeCompare(b.time)); const shown=[0,1,2,3,4].concat(sch.some(s=>Number(s.weekday)===5)?[5]:[], sch.some(s=>Number(s.weekday)===6)?[6]:[]); const canvas=document.createElement('canvas'), colW=260, W=shown.length*colW, H=760; canvas.width=W; canvas.height=H; const c=canvas.getContext('2d'); c.fillStyle='#f6fbfc'; c.fillRect(0,0,W,H); c.fillStyle='#17343b'; c.font='bold 26px Arial'; c.fillText('Planner Semanal',24,42); shown.forEach((day,idx)=>{const x=idx*colW+12; c.fillStyle='#0097B2'; c.fillRect(x,70,colW-24,44); c.fillStyle='white'; c.font='bold 18px Arial'; c.fillText(days[day],x+14,98); let y=132; const items=sch.filter(s=>Number(s.weekday)===day); if(!items.length){c.fillStyle='#66828a'; c.font='14px Arial'; c.fillText('Livre',x+14,y); return} items.forEach(s=>{c.fillStyle='white'; c.fillRect(x,y,colW-24,70); c.strokeStyle='#d9ecef'; c.strokeRect(x,y,colW-24,70); c.fillStyle='#0097B2'; c.font='bold 16px Arial'; c.fillText(s.time,x+12,y+24); c.fillStyle='#17343b'; c.font='15px Arial'; c.fillText((s.patientName||'').slice(0,24),x+12,y+46); y+=82})}); const a=document.createElement('a'); a.href=canvas.toDataURL('image/png'); a.download=`planner-semanal-${ymd(new Date())}.png`; a.click()}
async function downloadBackup(){const data=await exportDB();const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`backup-aba-${ymd(new Date())}.json`;a.click()}
async function uploadBackup(e){const file=e.target.files[0];if(!file)return;const text=await file.text();await importDB(JSON.parse(text));alert('Backup importado.');show('dashboard')}
if('serviceWorker' in navigator) navigator.serviceWorker.register('./service-worker.js');
openDB().then(()=>show('dashboard'));
$$('nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));
